# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Women Techmakers Galicia 2023 - 6 de Mayo, A Coruña"
email: "gdgcoruna@gmail.com"
description: "El 6 de Mayo celebramos la iniciativa Women Techmakers Galicia en A Coruña. Estamos buscando sponsors. Contamos contigo para hacer del mundo tecnológico de Galicia un lugar más diverso."
baseurl: ""
url: "https://wtm.gdggalicia.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-112660796-1"
googleAnalyticsSiteUrl: "wtm.gdggalicia.com"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Women Techmakers Galicia"
organizerAlternateName: "Women Techmakers Galicia"
organizerDescription: "GDG Galicia presenta
                       Día internacional de la mujer. Conecta. Crea. Celebra."
organizerEmail: "gdgcoruna@gmail.com"
organizerLogo: "/img/seo/wtmgalicia.png"
organizerLink: "https://www.meetup.com/en-AU/GDGVigo/?chapter_analytics_code=UA-73757047-1"

# Head
metaKeywords: "women, techmakers, wtm, galicia, event, gdg, google, programming, android, chrome, developers, lviv, mujer"
twitterAccount: "@gdggalicia"
socialImageSrcGooglePlus: "/img/seo/social-share.jpg"
socialImageSrcTwitter: "/img/seo/social-share.jpg"
socialImageSrcFacebook: "/img/seo/social-share.jpg"

# Documents
c4pUrl: "https://forms.gle/GQmi8gccrvwk7uwb7"
c4sponsorsUrl: "https://forms.gle/SRH2BBBTKNdkPpZL9"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/cod/", text: "Código de Conducta"}
 #- {permalink: "/schedule/", text: "Schedule"}
 #- {permalink: "/speakers/", text: "Speakers"}
 #- {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Ubicación"}
 #- {permalink: "/blog/", text: "Blog"}
 #- {permalink: "/nggirls/", text: "nggirls"}
#rightNavigationButtons:
 #- {link: "https://www.meetup.com/en-AU/GDGVigo/events/246829616/", text: "Get your ticket"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Women Techmakers Galicia <typeout> "
eventDate: "6 de Mayo, 2023, Fundación Luis Seoane, A Coruña"
typeoutTextValues: '"", "2023"'
typeoutFallback: "2023"
heroButtons:
 - {permalink: "https://www.meetup.com/gdg-coruna/events/292303423", text: "Consigue tu entrada"}

# About Block
aboutTitle: "Sobre WTM Galicia"
aboutBlock:
 - {title: "Conferencia", image: "conference.jpg", text: "WTM Galicia es un evento para celebrar el día de la mujer a través de una serie de charlas que nos harán aprender un montón de cosas nuevas en el mejor ambiente!" }
 - {title: "Networking", image: "networking.jpg", text: "Un modo genial de conocer a gente en el mundo tech y hacer networking!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Últimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 1
rockstarSpeakersTitle: "Speakers"
#rockstarSpeakersButtonText: "Envía tu propuesta"
#rockstarSpeakersButtonLink: "https://forms.gle/PaefR6diGzCihh256"


# Location Block
locationBlockTitle: "Ubicación"
eventLocationName: "A Coruña"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Rúa Cantón Grande, 9"
eventAddressLocality: "A Coruña"
eventAddressLocalityRegion: "A Coruña"
eventPostalCode: "15003"
eventAddressCountry: "Spain"
eventStartTime: "2023-05-06T10:00"
eventDoorTime: "09:30"
eventEndTime: "2023-05-06T17:30"
eventPlaceCoordinates: "43.368035, -8.403506"
mapCenterCoordinates: "43.368035, -8.403506"
mapMobileCenterCoordinates: "43.368035, -8.403506"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Estamos en twitter?"
twitterHashTag: "WTMGalicia"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Conviértete en sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdgvigo.us16.list-manage.com/subscribe/post?u=66b4bb03b0b8f95169952466e&amp;id=289252fea5"
subscribeInfo: "Registration will be open around beginning of February 2020. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Sponsorship"
ticketsOffers:
 -
  name: "Shy guy"
  price: "300"
  priceCurrency: "€"
  ticketsNumber: "350"
  buyButtonLink: "https://forms.gle/GQmi8gccrvwk7uwb7"
  buyButtonText: "Sponsor us now!"
  ticketContentList: ["Support women in tech", "Logo on website", "Shared slide"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Big boss"
  price: "1000"
  priceCurrency: "€"
  ticketsNumber: "1000"
  featured: true
  buyButtonLink: "https://forms.gle/GQmi8gccrvwk7uwb7"
  buyButtonText: "Sponsor us now!"
  ticketContentList: ["Everything from High five ", "Logo on T-Shirt", "Logo on videos that are recorded", "Hiring booth at venue"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
 -
  name: "High five"
  price: "700"
  priceCurrency: "€"
  ticketsNumber: "700"
  buyButtonLink: "https://forms.gle/GQmi8gccrvwk7uwb7"
  buyButtonText: "Sponsor us now!"
#  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Everything from Shy guy", "Your own slide", "Social Media mention"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/communities/104458805154699272096", icon: "google-plus"}
 - {link: "https://twitter.com/GDGVigo", icon: "twitter"}
 - {link: "https://www.facebook.com/googledevelopergroupvigo/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:gdgcoruna@gmail.com", text: "gdgcoruna@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conducta"}

# Blog
blogTitle: "Últimas noticias"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "We are a small but ambitious team with big dreams. We love what we do and we do it because of the community. So now it is our turn to give back to the community!"

# Logistics Find Way Block
findWayTitle: "¿Cómo llegar?"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "42.237904, -8.720964"
logisticsMapMobileCenterCoordinates: "42.237904, -8.720964"
logisticsMapAutoDirections: false
googleMapsApiKey: "AIzaSyCKZiS4sRf0EO86qoQvCJIJTnjvN3qdMPA"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "¿Cómo llegar a A Coruña?"
directionDetailsCards:
 #- {title: "From the Airport", information: 'Airport is right at the city border. It is easy to reach by car, public transport or taxi. More information is available at <a href="http://www.aena.es/es/aeropuerto-vigo/transporte-y-parking.html">airport website</a>.'}
 - {title: "Transporte público", information: 'Google Transit está disponible en A Coruña, así que puedes utilizar Google Maps para moverte. A Coruña es una ciudad de tamaño medio así que seguramente puedas moverte a pie en tus desplazamientos.'}
 #- {title: "Hoteles", information: 'A Coruña cuenta con un montón de hoteles y apartamentos. More information will be available later.'}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.056728, 3.117289"
hackathonMapCenterCoordinates: "49.056728, 3.117289"
hackathonMapMobileCenterCoordinates: "49.056728, 3.117289"
